networks:
  - network: polkadot
    candidate_hostname: https://polkadot.w3f.community/candidates
    chaindata_hostname: wss://rpc.polkadot.io
    watch_targets:
      - 14Ns6kKbCoka3MS4Hn6b7oRw9fFejG8RH5rq5j63cWUfpPDJ
      - 12RYJb5gG4hfoWPK3owEYtmWoko8G6zwYpvDYTyXFVSfJr8Y
      - 16GMHo9HZv8CcJy4WLoMaU9qusgzx2wxKDLbXStEBvt5274B
  - network: kusama
    candidate_hostname: https://kusama.w3f.community/candidates
    chaindata_hostname: wss://kusama-rpc.polkadot.io
    watch_targets:
      - G1rrUNQSk7CjjEmLSGcpNu72tVtyzbWdUvgmSer9eBitXWf
      - HgTtJusFEn2gmMmB5wmJDnMRXKD6dzqCpNR7a99kkQ7BNvX
      - EX9uchmfeSqKTM7cMMg8DkH49XV8i4R7a7rqCn8btpZBHDP
      - H4635Bjj3X7TjnQhd55p9DyFPK39JiRypmCnsDhS3NHSMS5
      - Hs94zeHrSUWG1VBzsvHPxR2VRN5mq1Rib1PEfjH7wkGzv2Z
      - CdWjVn5J9ct4D3yK8HbwXmmGyLcxjkDitaBLxwH5g5Vh7pi
      - HxRmQTVrMxMkhyZquYLu2hSL1QDYvVwSpDfBHvVJhEMVzRj
      - FJbKWFGCfZFZiNQtAZ5uqbUhKeB3P3a6RVRw6GqTbgiqtem
